### ISSUE TITLE
DataFusion 37.0.0 upgrade

### ISSUE THREAD

**Issue by comphead** [apache/datafusion-comet#222]
### What is the problem the feature request solves?

Prepare Comet to DataFusion 37.0.0 upgrade

### Additional context

Depends on https://github.com/apache/arrow-datafusion/pull/9697

**Comment by comphead** [comment]
Related to https://github.com/apache/arrow-datafusion-comet/pull/239/files

**Comment by viirya** [comment]
Yea, as #239 is going to use specified arrow-rs and DataFusion branch to work around a Java Arrow bug, we can hold on upgrading these dependencies.

The fix of the bug is merged into Java Arrow. Once it is released and we upgrade it in Comet, we can change back to normal released arrow-rs and DataFusion releases. Thanks.

**Comment by andygrove** [comment]
Comet is now using 39.0.0-rc1 (and will upgrade to 39.0.0 when it is available, probably early next week) so I think we can close this issue now
